//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIKit_UIManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIKit.UIManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Destroy", Destroy);
		L.RegFunction("Close", Close);
		L.RegFunction("Open", Open);
		L.RegFunction("Query", Query);
		L.RegFunction("IsOpen", IsOpen);
		L.RegFunction("UpdateFixedSortingOrder", UpdateFixedSortingOrder);
		L.RegFunction("UpdateOptCullUI", UpdateOptCullUI);
		L.RegFunction("ClearOptCullUI", ClearOptCullUI);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("UICameraName", get_UICameraName, null);
		L.RegVar("Adapter_Pool_Name", get_Adapter_Pool_Name, null);
		L.RegConstant("SortingOrderBoundary", 20000);
		L.RegVar("IsRunUGUI", get_IsRunUGUI, set_IsRunUGUI);
		L.RegVar("Instance", get_Instance, null);
		L.RegVar("UIRoot", get_UIRoot, null);
		L.RegVar("UICamera", get_UICamera, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Destroy(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
				obj.Destroy();
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<bool>(L, 2))
			{
				UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
				bool arg0 = LuaDLL.lua_toboolean(L, 2);
				obj.Destroy(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
				string arg0 = ToLua.ToString(L, 2);
				bool o = obj.Destroy(arg0);
				LuaDLL.lua_pushboolean(L, o);
				return 1;
			}
			else if (count == 3)
			{
				UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
				bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
				bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
				obj.Destroy(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UIKit.UIManager.Destroy");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Close(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			obj.Close(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Open(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.Open(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Query(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			UnityEngine.GameObject o = obj.Query(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsOpen(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsOpen(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateFixedSortingOrder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 3);
			obj.UpdateFixedSortingOrder(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateOptCullUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.UpdateOptCullUI(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearOptCullUI(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.UIManager obj = (UIKit.UIManager)ToLua.CheckObject(L, 1, typeof(UIKit.UIManager));
			string arg0 = ToLua.CheckString(L, 2);
			obj.ClearOptCullUI(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UICameraName(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UIKit.UIManager.UICameraName);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Adapter_Pool_Name(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushstring(L, UIKit.UIManager.Adapter_Pool_Name);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_IsRunUGUI(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushboolean(L, UIKit.UIManager.IsRunUGUI);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, UIKit.UIManager.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UIRoot(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, UIKit.UIManager.UIRoot);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UICamera(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, UIKit.UIManager.UICamera);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_IsRunUGUI(IntPtr L)
	{
		try
		{
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			UIKit.UIManager.IsRunUGUI = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

