//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UIKit_LocalisationManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UIKit.LocalisationManager), typeof(System.Object));
		L.RegFunction("Instance", Instance);
		L.RegFunction("AddText", AddText);
		L.RegFunction("RemoveText", RemoveText);
		L.RegFunction("UpdateTheme", UpdateTheme);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Instance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			UIKit.LocalisationManager o = UIKit.LocalisationManager.Instance();
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int AddText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.LocalisationManager obj = (UIKit.LocalisationManager)ToLua.CheckObject(L, 1, typeof(UIKit.LocalisationManager));
			UIKit.LocalisationText arg0 = (UIKit.LocalisationText)ToLua.CheckObject(L, 2, typeof(UIKit.LocalisationText));
			obj.AddText(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RemoveText(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UIKit.LocalisationManager obj = (UIKit.LocalisationManager)ToLua.CheckObject(L, 1, typeof(UIKit.LocalisationManager));
			UIKit.LocalisationText arg0 = (UIKit.LocalisationText)ToLua.CheckObject(L, 2, typeof(UIKit.LocalisationText));
			obj.RemoveText(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateTheme(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UIKit.LocalisationManager obj = (UIKit.LocalisationManager)ToLua.CheckObject(L, 1, typeof(UIKit.LocalisationManager));
				obj.UpdateTheme();
				return 0;
			}
			else if (count == 2)
			{
				UIKit.LocalisationManager obj = (UIKit.LocalisationManager)ToLua.CheckObject(L, 1, typeof(UIKit.LocalisationManager));
				UIKit.ThemeArea arg0 = (UIKit.ThemeArea)ToLua.CheckObject(L, 2, typeof(UIKit.ThemeArea));
				obj.UpdateTheme(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UIKit.LocalisationManager.UpdateTheme");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

